from typing import Protocol
from scanner.models import Candle, Liquidity


class MarketData(Protocol):
    def products(self) -> list[str]: ...
    def candles(self, symbol: str, start: int, end: int, timeframe: int) -> list[Candle]: ...
    def liquidity(self, symbol: str) -> Liquidity: ...
